- name: Cat localhost
  hosts: localhost
  tasks:
    - name: Print inventory file
      ansible.builtin.debug:
        msg: "the value of foo.txt is {{ lookup('ansible.builtin.file', '/runner/inventory/hosts') }}"
- name: Test
  hosts: web
  tasks:
    - name: Copy using inline content
      ansible.builtin.copy:
        content: '# This file was moved to /etc/other.conf'
        dest: /tmp/test.txt
    - name: Fetch file
      ansible.builtin.fetch:
        src: /tmp/test.txt
        dest: test.txt
        flat: true
      register: file
    - name: Debug
      ansible.builtin.debug:
        var: file
      